# Generated by Django 2.2.26 on 2022-03-21 21:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('imagenest', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Submission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='images/')),
                ('creation_time', models.DateTimeField(auto_now_add=True)),
                ('like_count', models.PositiveIntegerField(default=0)),
                ('likers', models.ManyToManyField(related_name='favorites', to='imagenest.UserProfile')),
                ('uploader', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='imagenest.UserProfile')),
            ],
            options={
                'ordering': ['-creation_time'],
            },
        ),
        migrations.DeleteModel(
            name='upload',
        ),
    ]
