# Generated by Django 2.2.26 on 2022-03-20 22:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('imagenest', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Post',
        ),
    ]
